import type { AppState } from "../types";

export const DEFAULT: AppState = {
  onboarded: false,
  firstWinPending: false,
  onboardStep: 0,
  userName: "",
  weeklyTarget: 3,
  bodyStats: { weight: "", height: "", age: "", waist: "", unit: "metric", sex: "" },
  tone: "Balanced",
  day: 1,
  week: 1,
  christianLens: false,
  whys: [],
  checkIn: null,
  checkInDate: null,
  aiInsight: null,
  aiLoading: false,
  sessionHistory: [],
  currentSession: null,
  sessionLoading: false,
  trainingLocation: "bodyweight",
  equipment: ["bodyweight"],
  injuries: [],
  meals: [],
  sleepLog: [],
  sobriety: null,
  goals: [],
  steps: 0,
  communityPosts: [
    { id: 1, user: "M.", day: 22, pillar: "The Trickle", text: "Third walk this week. Nothing heroic. Just consistent.", seen: [], flagged: false },
    { id: 2, user: "D.", day: 7, pillar: "Thrownness", text: "First time I named the pattern. Harder than I expected.", seen: [], flagged: false },
    { id: 3, user: "K.", day: 45, pillar: "Radical Responsibility", text: "Moved the appointment I kept postponing. One small thing.", seen: [], flagged: false },
  ],
  buddy: null,
  weeklyDigest: null,
  digestLoading: false,
  spotifyConnected: false,
  cravingLog: [],
  tutorialSeen: false,
  quoteCycle: 0,
  isPremium: false,
  email: "",
  emailCaptured: false,
  emailPromptDismissed: false,
};
